import { Address } from "@ton/core";

export const CRYPTOCASH_MARKETING_PROGRAM_ADDRESS =
  "EQCFZmVrYR-tLGIWDHjBb-Oyk1tcePk2_ThcytEZA08dNLbO";
export const MULTI_MARKETING_PROGRAM_ADDRESS =
  "EQCayDLxd-C3iOB051M5FUHx565Xyjt4vwArt2VPYkIOlbQ5";
export const NEO_MARKETING_PROGRAM_ADDRESS =
  "EQBPL8ZEpsPCOJ44z40F-DS_ZDgDazslM79D7s1DQj7g-AR3";

export const LIFESTYLER_MARKETING_PROGRAM_ADDRESS =
  "EQCwxHXH1C-rzFnEk0-KmNmDUOQonObpRQuB2WL5OOafllVm";
export const SILVER_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQB2US7eWirf-V-rt621Dx8fNX-fPswcJoaTqoA9jwRmo1pN";
export const GOLD_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQDt077hnquwG159d2J6ZrkZe8YFcJiCjxo3qjIhJfNfBxF_";
export const ELITE_MARKETING_PROGRAM_ADDRESS =
  "EQAd1MMEpc-1Tmazd3syt2layZaHRAxwQvY8h4IYlxvmUdnE";
export const MINI_MARKETING_PROGRAM_ADDRESS =
  "EQBLp3ANri8oiB-78S7SmWBRVf4uFW7GwFyRoaQji5VkpuPB";
export const SUPER_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQBRnTw_z7zVkDjRQNLF2ZfMZWo5KpNURviODVwc7Ld9nTSz";
export const FLASH_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQC_KI3G4diI_eTmj8fX59V7tpFrx6qz0jcQE0XOgIAmD3l9";

export const AVAILABLE_TEST_PROGRAM_ADDRESSES = [
  LIFESTYLER_MARKETING_PROGRAM_ADDRESS,
  SILVER_MATRIX_MARKETING_PROGRAM_ADDRESS,
  GOLD_MATRIX_MARKETING_PROGRAM_ADDRESS,
  ELITE_MARKETING_PROGRAM_ADDRESS,
  MINI_MARKETING_PROGRAM_ADDRESS,
  SUPER_MATRIX_MARKETING_PROGRAM_ADDRESS,
  FLASH_MATRIX_MARKETING_PROGRAM_ADDRESS,
] as const;

const PROGRAM_KEYS_BY_ADDRESS = new Map<string, "multi" | "neo">([
  [Address.parse(MULTI_MARKETING_PROGRAM_ADDRESS).toRawString(), "multi"],
  [Address.parse(NEO_MARKETING_PROGRAM_ADDRESS).toRawString(), "neo"],
]);

export function getLegacyPricingProgramKey(
  marketingAddress: string,
): "multi" | "neo" | null {
  try {
    return (
      PROGRAM_KEYS_BY_ADDRESS.get(
        Address.parse(marketingAddress).toRawString(),
      ) ?? null
    );
  } catch {
    return null;
  }
}
