import { Address } from "@ton/core";

export const ACTUAL_CRYPTOCASH_MARKETING_PROGRAM_ADDRESS =
  "EQAba1dNyAbxm4t_dv5T1ARQXaQAAYcfJ4jcAWcw1PQ7q10b";
export const ACTUAL_MULTI_MARKETING_PROGRAM_ADDRESS =
  "EQBti82_Lya2Wz-iAwuFDH-vdoT0N1RfiBjkrnbhFbkc2Wfu";
export const ACTUAL_NEO_MARKETING_PROGRAM_ADDRESS =
  "EQCQUF6o3Z_SzFD5m9aR6uGbIgaujaUcHTPX9oghh8O4lMYh";

export const TEST_CRYPTOCASH_MARKETING_PROGRAM_ADDRESS =
  "EQCFZmVrYR-tLGIWDHjBb-Oyk1tcePk2_ThcytEZA08dNLbO";
export const TEST_LIFESTYLER_MARKETING_PROGRAM_ADDRESS =
  "EQCwxHXH1C-rzFnEk0-KmNmDUOQonObpRQuB2WL5OOafllVm";
export const TEST_SILVER_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQB2US7eWirf-V-rt621Dx8fNX-fPswcJoaTqoA9jwRmo1pN";
export const TEST_GOLD_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQDt077hnquwG159d2J6ZrkZe8YFcJiCjxo3qjIhJfNfBxF_";
export const TEST_ELITE_MARKETING_PROGRAM_ADDRESS =
  "EQAd1MMEpc-1Tmazd3syt2layZaHRAxwQvY8h4IYlxvmUdnE";
export const TEST_MINI_MARKETING_PROGRAM_ADDRESS =
  "EQBLp3ANri8oiB-78S7SmWBRVf4uFW7GwFyRoaQji5VkpuPB";
export const TEST_SUPER_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQBRnTw_z7zVkDjRQNLF2ZfMZWo5KpNURviODVwc7Ld9nTSz";
export const TEST_FLASH_MATRIX_MARKETING_PROGRAM_ADDRESS =
  "EQC_KI3G4diI_eTmj8fX59V7tpFrx6qz0jcQE0XOgIAmD3l9";

export const TEST_PROGRAM_ADDRESSES = [
  TEST_CRYPTOCASH_MARKETING_PROGRAM_ADDRESS,
  TEST_LIFESTYLER_MARKETING_PROGRAM_ADDRESS,
  TEST_SILVER_MATRIX_MARKETING_PROGRAM_ADDRESS,
  TEST_GOLD_MATRIX_MARKETING_PROGRAM_ADDRESS,
  TEST_ELITE_MARKETING_PROGRAM_ADDRESS,
  TEST_MINI_MARKETING_PROGRAM_ADDRESS,
  TEST_SUPER_MATRIX_MARKETING_PROGRAM_ADDRESS,
  TEST_FLASH_MATRIX_MARKETING_PROGRAM_ADDRESS,
] as const;

const PROGRAM_KEYS_BY_ADDRESS = new Map<string, "multi" | "neo">([
  [Address.parse(ACTUAL_MULTI_MARKETING_PROGRAM_ADDRESS).toRawString(), "multi"],
  [Address.parse(ACTUAL_NEO_MARKETING_PROGRAM_ADDRESS).toRawString(), "neo"],
]);

export function getLegacyPricingProgramKey(
  marketingAddress: string,
): "multi" | "neo" | null {
  try {
    return (
      PROGRAM_KEYS_BY_ADDRESS.get(
        Address.parse(marketingAddress).toRawString(),
      ) ?? null
    );
  } catch {
    return null;
  }
}
